### ISSUE TITLE
ERROR:root:(127.0.0.1:35043) failed to connect: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by raozhongyu** [twsq/sam-driving#1]
Thank for your great job, I meet this problem "ERROR:root:(127.0.0.1:35043) failed to connect: [Errno 111] Connection refused"
I'm sorry for i'm not familar with docker.

**Comment by twsq** [comment]
Regarding this error, I have also encountered it in the past. I would advise quitting and restarting and seeing if that works.

**Comment by twsq** [comment]
Oops, I misread the error message. In general, if the evaluation crashes, I would advise quitting and restarting and seeing if that works. However, for this particular issue "Connection refused", the fix is to build the CARLA Gear Docker using an older version of the Release.Dockerfile from the main CARLA repo (commit: cfc6ee6fa11671778116bd89aef4539a166ec918). If you are not using Ubuntu 16.04, you should modify the first line of this Dockerfile accordingly before building CARLA Gear. I have updated the README to fix this issue.

**Comment by raozhongyu** [comment]
Thanks for your reply！
